export const Routes = {
  landing: "/Landing",
  login: "/Login",
  signInUp: "/Sign In",
  userProfile: "/profile",
  editUserProfile: "/user_profile/EditUserProfile",
  mapSearch: "/jobs/MapSearch",
  viewJobDetails: "/jobs/ViewJobDetails",
  viewAllJobs: "/jobs/ViewAllJobs",
  myPostedJobs: "/jobs/MyPostedJobs",
  register: "/Login?mode=signup",
  viewAllSeekers: "/jobs/ViewAllJobs?view=seekers",
  viewJobSeekerDetails: "/seekers/ViewJobSeekerDetail",
  postJob: "/jobs/PostAJob",
  editSeeekerForm: "/user_profile/EditSeekerProfile",
  contactUs: "/ContactUs",
  privacyPolicy: "/PrivacyPolicy",
  termsNConditions: "/TermsNConditions",
  AdminContactDetails: "/admin/ContactUsDetails",
  AdminUserDetails: "/admin/UserDetails",
  AdminEditUserDetails: "/admin/EditUserDetails",
  AdminBuildUserDetails: "/admin/BuildProfile",
  AdminDashboard: "/admin/Dashboard",
  AdminJobPost: "/admin/AdminPostAjob",
  AdminMyJobPost: "/admin/AdminMyPostedJob",
  aboutUs: "/about",
  resources: "/resources",
  messages: "/Messages",
};
