export const Routes = {
  landing: "/Landing",
  login: "/Login",
  signInUp: "/Sign In",
  userProfile: "/user_profile/UserProfile",
  editUserProfile: "/user_profile/EditUserProfile",
  mapSearch: "/jobs/MapSearch",
  viewJobDetails: "/jobs/ViewJobDetails",
  viewAllJobs: "/jobs/ViewAllJobs",
  myPostedJobs: "/jobs/MyPostedJobs",
  register:"/Register",
  viewAllSeekers: "/seekers/ViewAllSeekers",
  viewJobSeekerDetails: "/seekers/ViewJobSeekerDetail",
  postJob : "/jobs/PostAJob",
  editSeeekerForm:"/user_profile/EditSeekerProfile",
  contactUs:"/ContactUs",
  privacyPolicy:"/PrivacyPolicy",
  termsNConditions:"/TermsNConditions",
  AdminContactDetails:"/admin/ContactUsDetails",
  AdminUserDetails:"/admin/UserDetails",
  AdminEditUserDetails: "/admin/EditUserDetails",
  AdminBuildUserDetails: "/admin/BuildProfile",
  AdminDashboard: "/admin/Dashboard",
  AdminJobPost: "/admin/AdminPostAjob",
  AdminMyJobPost: "/admin/AdminMyPostedJob",
};
